### ISSUE TITLE
[telegram] - disallow use of /mempool /version lookups to non connect user ids

### ISSUE THREAD

**Issue by asvdf** [alexbosworth/balanceofsatoshis#281]
Just for fun, I tried chatting with my bot from another telegram account.
I could make it return list of commands with `/start` and get mempool reports. Obviously all sensitive functions were unavailable and requested authorization, still I would think one could DDoS the node with a concerted flood of `/mempool` commands. Probably even get it banned from telegram for flooding itself, as it would be sending a lot of messages in a short time in reply to all the incoming commands.

It might be a good idea to have the bot simply ignore/drop any incoming messages by anyone other than the authorized and connected user id.

**Comment by alexbosworth** [comment]
It wouldn't work with the current model to totally ignore external users because when you initially start using the bot you use the /connect command and that comes from an unknown user

You can mitigate this kind of thing by running the tg bot on a separate instance, this way it has no impact on your node since it's just relaying the mempool info from mempool.space and not touching your node at all, and then also by not sharing your bot username

**Comment by asvdf** [comment]
True, true, this is the reason I suggested enabling the "ignore" flag after the bot has successfully connected and is working with an existing TG user; before that it would need to accept messages by anyone.
I feel it's not much of a risk, not more than in itself having Telegram know everything that happens on LN through the bots, still I know it would be something I wanted to plug if I was able to. No big deal anyway 😎

**Comment by asvdf** [comment]
Great for the merge by Nitesh :)
I still strongly think that, once the bot has been started with `--connect <userid>` and the msssage is received from a different userid, then the bot should just drop the message with no reply at all, instead of inviting the user to authorize, implicitly letting them know it's a bos telegram both they just messaged

**Comment by alexbosworth** [comment]
Sounds reasonable
